/**
 *
 *  Indicator.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Indicator.h"
#include "Counter.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Indicator::Cols::_id = "id";
const std::string Indicator::Cols::_id_counter = "id_counter";
const std::string Indicator::Cols::_year = "year";
const std::string Indicator::Cols::_month = "month";
const std::string Indicator::Cols::_day = "day";
const std::string Indicator::Cols::_hour = "hour";
const std::string Indicator::Cols::_minute = "minute";
const std::string Indicator::Cols::_second = "second";
const std::string Indicator::Cols::_T1 = "T1";
const std::string Indicator::Cols::_T2 = "T2";
const std::string Indicator::primaryKeyName = "id";
const bool Indicator::hasPrimaryKey = true;
const std::string Indicator::tableName = "indicator";

const std::vector<typename Indicator::MetaData> Indicator::metaData_={
{"id","uint64_t","integer",8,1,1,0},
{"id_counter","uint64_t","integer",8,0,0,0},
{"year","uint64_t","integer",8,0,0,0},
{"month","uint64_t","integer",8,0,0,0},
{"day","uint64_t","integer",8,0,0,0},
{"hour","uint64_t","integer",8,0,0,0},
{"minute","uint64_t","integer",8,0,0,0},
{"second","uint64_t","integer",8,0,0,0},
{"T1","uint64_t","integer",8,0,0,0},
{"T2","uint64_t","integer",8,0,0,0}
};
const std::string &Indicator::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Indicator::Indicator(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<uint64_t>(r["id"].as<uint64_t>());
        }
        if(!r["id_counter"].isNull())
        {
            idCounter_=std::make_shared<uint64_t>(r["id_counter"].as<uint64_t>());
        }
        if(!r["year"].isNull())
        {
            year_=std::make_shared<uint64_t>(r["year"].as<uint64_t>());
        }
        if(!r["month"].isNull())
        {
            month_=std::make_shared<uint64_t>(r["month"].as<uint64_t>());
        }
        if(!r["day"].isNull())
        {
            day_=std::make_shared<uint64_t>(r["day"].as<uint64_t>());
        }
        if(!r["hour"].isNull())
        {
            hour_=std::make_shared<uint64_t>(r["hour"].as<uint64_t>());
        }
        if(!r["minute"].isNull())
        {
            minute_=std::make_shared<uint64_t>(r["minute"].as<uint64_t>());
        }
        if(!r["second"].isNull())
        {
            second_=std::make_shared<uint64_t>(r["second"].as<uint64_t>());
        }
        if(!r["T1"].isNull())
        {
            t1_=std::make_shared<uint64_t>(r["T1"].as<uint64_t>());
        }
        if(!r["T2"].isNull())
        {
            t2_=std::make_shared<uint64_t>(r["T2"].as<uint64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            idCounter_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            year_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            month_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            day_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            hour_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            minute_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            second_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            t1_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            t2_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
    }

}

Indicator::Indicator(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idCounter_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            year_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            month_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            day_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[4]].asUInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            hour_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[5]].asUInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            minute_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            second_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[7]].asUInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            t1_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            t2_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[9]].asUInt64());
        }
    }
}

Indicator::Indicator(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("id_counter"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["id_counter"].isNull())
        {
            idCounter_=std::make_shared<uint64_t>((uint64_t)pJson["id_counter"].asUInt64());
        }
    }
    if(pJson.isMember("year"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["year"].isNull())
        {
            year_=std::make_shared<uint64_t>((uint64_t)pJson["year"].asUInt64());
        }
    }
    if(pJson.isMember("month"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["month"].isNull())
        {
            month_=std::make_shared<uint64_t>((uint64_t)pJson["month"].asUInt64());
        }
    }
    if(pJson.isMember("day"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["day"].isNull())
        {
            day_=std::make_shared<uint64_t>((uint64_t)pJson["day"].asUInt64());
        }
    }
    if(pJson.isMember("hour"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["hour"].isNull())
        {
            hour_=std::make_shared<uint64_t>((uint64_t)pJson["hour"].asUInt64());
        }
    }
    if(pJson.isMember("minute"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["minute"].isNull())
        {
            minute_=std::make_shared<uint64_t>((uint64_t)pJson["minute"].asUInt64());
        }
    }
    if(pJson.isMember("second"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["second"].isNull())
        {
            second_=std::make_shared<uint64_t>((uint64_t)pJson["second"].asUInt64());
        }
    }
    if(pJson.isMember("T1"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["T1"].isNull())
        {
            t1_=std::make_shared<uint64_t>((uint64_t)pJson["T1"].asUInt64());
        }
    }
    if(pJson.isMember("T2"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["T2"].isNull())
        {
            t2_=std::make_shared<uint64_t>((uint64_t)pJson["T2"].asUInt64());
        }
    }
}

void Indicator::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            idCounter_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            year_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            month_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            day_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[4]].asUInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            hour_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[5]].asUInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            minute_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            second_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[7]].asUInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            t1_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            t2_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[9]].asUInt64());
        }
    }
}

void Indicator::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("id_counter"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["id_counter"].isNull())
        {
            idCounter_=std::make_shared<uint64_t>((uint64_t)pJson["id_counter"].asUInt64());
        }
    }
    if(pJson.isMember("year"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["year"].isNull())
        {
            year_=std::make_shared<uint64_t>((uint64_t)pJson["year"].asUInt64());
        }
    }
    if(pJson.isMember("month"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["month"].isNull())
        {
            month_=std::make_shared<uint64_t>((uint64_t)pJson["month"].asUInt64());
        }
    }
    if(pJson.isMember("day"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["day"].isNull())
        {
            day_=std::make_shared<uint64_t>((uint64_t)pJson["day"].asUInt64());
        }
    }
    if(pJson.isMember("hour"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["hour"].isNull())
        {
            hour_=std::make_shared<uint64_t>((uint64_t)pJson["hour"].asUInt64());
        }
    }
    if(pJson.isMember("minute"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["minute"].isNull())
        {
            minute_=std::make_shared<uint64_t>((uint64_t)pJson["minute"].asUInt64());
        }
    }
    if(pJson.isMember("second"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["second"].isNull())
        {
            second_=std::make_shared<uint64_t>((uint64_t)pJson["second"].asUInt64());
        }
    }
    if(pJson.isMember("T1"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["T1"].isNull())
        {
            t1_=std::make_shared<uint64_t>((uint64_t)pJson["T1"].asUInt64());
        }
    }
    if(pJson.isMember("T2"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["T2"].isNull())
        {
            t2_=std::make_shared<uint64_t>((uint64_t)pJson["T2"].asUInt64());
        }
    }
}

const uint64_t &Indicator::getValueOfId() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getId() const noexcept
{
    return id_;
}
void Indicator::setId(const uint64_t &pId) noexcept
{
    id_ = std::make_shared<uint64_t>(pId);
    dirtyFlag_[0] = true;
}
void Indicator::setIdToNull() noexcept
{
    id_.reset();
    dirtyFlag_[0] = true;
}
const typename Indicator::PrimaryKeyType & Indicator::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const uint64_t &Indicator::getValueOfIdCounter() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(idCounter_)
        return *idCounter_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getIdCounter() const noexcept
{
    return idCounter_;
}
void Indicator::setIdCounter(const uint64_t &pIdCounter) noexcept
{
    idCounter_ = std::make_shared<uint64_t>(pIdCounter);
    dirtyFlag_[1] = true;
}
void Indicator::setIdCounterToNull() noexcept
{
    idCounter_.reset();
    dirtyFlag_[1] = true;
}

const uint64_t &Indicator::getValueOfYear() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(year_)
        return *year_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getYear() const noexcept
{
    return year_;
}
void Indicator::setYear(const uint64_t &pYear) noexcept
{
    year_ = std::make_shared<uint64_t>(pYear);
    dirtyFlag_[2] = true;
}
void Indicator::setYearToNull() noexcept
{
    year_.reset();
    dirtyFlag_[2] = true;
}

const uint64_t &Indicator::getValueOfMonth() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(month_)
        return *month_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getMonth() const noexcept
{
    return month_;
}
void Indicator::setMonth(const uint64_t &pMonth) noexcept
{
    month_ = std::make_shared<uint64_t>(pMonth);
    dirtyFlag_[3] = true;
}
void Indicator::setMonthToNull() noexcept
{
    month_.reset();
    dirtyFlag_[3] = true;
}

const uint64_t &Indicator::getValueOfDay() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(day_)
        return *day_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getDay() const noexcept
{
    return day_;
}
void Indicator::setDay(const uint64_t &pDay) noexcept
{
    day_ = std::make_shared<uint64_t>(pDay);
    dirtyFlag_[4] = true;
}
void Indicator::setDayToNull() noexcept
{
    day_.reset();
    dirtyFlag_[4] = true;
}

const uint64_t &Indicator::getValueOfHour() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(hour_)
        return *hour_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getHour() const noexcept
{
    return hour_;
}
void Indicator::setHour(const uint64_t &pHour) noexcept
{
    hour_ = std::make_shared<uint64_t>(pHour);
    dirtyFlag_[5] = true;
}
void Indicator::setHourToNull() noexcept
{
    hour_.reset();
    dirtyFlag_[5] = true;
}

const uint64_t &Indicator::getValueOfMinute() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(minute_)
        return *minute_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getMinute() const noexcept
{
    return minute_;
}
void Indicator::setMinute(const uint64_t &pMinute) noexcept
{
    minute_ = std::make_shared<uint64_t>(pMinute);
    dirtyFlag_[6] = true;
}
void Indicator::setMinuteToNull() noexcept
{
    minute_.reset();
    dirtyFlag_[6] = true;
}

const uint64_t &Indicator::getValueOfSecond() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(second_)
        return *second_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getSecond() const noexcept
{
    return second_;
}
void Indicator::setSecond(const uint64_t &pSecond) noexcept
{
    second_ = std::make_shared<uint64_t>(pSecond);
    dirtyFlag_[7] = true;
}
void Indicator::setSecondToNull() noexcept
{
    second_.reset();
    dirtyFlag_[7] = true;
}

const uint64_t &Indicator::getValueOfT1() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(t1_)
        return *t1_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getT1() const noexcept
{
    return t1_;
}
void Indicator::setT1(const uint64_t &pT1) noexcept
{
    t1_ = std::make_shared<uint64_t>(pT1);
    dirtyFlag_[8] = true;
}
void Indicator::setT1ToNull() noexcept
{
    t1_.reset();
    dirtyFlag_[8] = true;
}

const uint64_t &Indicator::getValueOfT2() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(t2_)
        return *t2_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Indicator::getT2() const noexcept
{
    return t2_;
}
void Indicator::setT2(const uint64_t &pT2) noexcept
{
    t2_ = std::make_shared<uint64_t>(pT2);
    dirtyFlag_[9] = true;
}
void Indicator::setT2ToNull() noexcept
{
    t2_.reset();
    dirtyFlag_[9] = true;
}

void Indicator::updateId(const uint64_t id)
{
    id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string> &Indicator::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id_counter",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "second",
        "T1",
        "T2"
    };
    return inCols;
}

void Indicator::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdCounter())
        {
            binder << getValueOfIdCounter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getYear())
        {
            binder << getValueOfYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonth())
        {
            binder << getValueOfMonth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDay())
        {
            binder << getValueOfDay();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getHour())
        {
            binder << getValueOfHour();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMinute())
        {
            binder << getValueOfMinute();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSecond())
        {
            binder << getValueOfSecond();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getT1())
        {
            binder << getValueOfT1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getT2())
        {
            binder << getValueOfT2();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Indicator::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void Indicator::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getIdCounter())
        {
            binder << getValueOfIdCounter();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getYear())
        {
            binder << getValueOfYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMonth())
        {
            binder << getValueOfMonth();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getDay())
        {
            binder << getValueOfDay();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getHour())
        {
            binder << getValueOfHour();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMinute())
        {
            binder << getValueOfMinute();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSecond())
        {
            binder << getValueOfSecond();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getT1())
        {
            binder << getValueOfT1();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getT2())
        {
            binder << getValueOfT2();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Indicator::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdCounter())
    {
        ret["id_counter"]=(Json::UInt64)getValueOfIdCounter();
    }
    else
    {
        ret["id_counter"]=Json::Value();
    }
    if(getYear())
    {
        ret["year"]=(Json::UInt64)getValueOfYear();
    }
    else
    {
        ret["year"]=Json::Value();
    }
    if(getMonth())
    {
        ret["month"]=(Json::UInt64)getValueOfMonth();
    }
    else
    {
        ret["month"]=Json::Value();
    }
    if(getDay())
    {
        ret["day"]=(Json::UInt64)getValueOfDay();
    }
    else
    {
        ret["day"]=Json::Value();
    }
    if(getHour())
    {
        ret["hour"]=(Json::UInt64)getValueOfHour();
    }
    else
    {
        ret["hour"]=Json::Value();
    }
    if(getMinute())
    {
        ret["minute"]=(Json::UInt64)getValueOfMinute();
    }
    else
    {
        ret["minute"]=Json::Value();
    }
    if(getSecond())
    {
        ret["second"]=(Json::UInt64)getValueOfSecond();
    }
    else
    {
        ret["second"]=Json::Value();
    }
    if(getT1())
    {
        ret["T1"]=(Json::UInt64)getValueOfT1();
    }
    else
    {
        ret["T1"]=Json::Value();
    }
    if(getT2())
    {
        ret["T2"]=(Json::UInt64)getValueOfT2();
    }
    else
    {
        ret["T2"]=Json::Value();
    }
    return ret;
}

Json::Value Indicator::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getIdCounter())
            {
                ret[pMasqueradingVector[1]]=(Json::UInt64)getValueOfIdCounter();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getYear())
            {
                ret[pMasqueradingVector[2]]=(Json::UInt64)getValueOfYear();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMonth())
            {
                ret[pMasqueradingVector[3]]=(Json::UInt64)getValueOfMonth();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getDay())
            {
                ret[pMasqueradingVector[4]]=(Json::UInt64)getValueOfDay();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getHour())
            {
                ret[pMasqueradingVector[5]]=(Json::UInt64)getValueOfHour();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMinute())
            {
                ret[pMasqueradingVector[6]]=(Json::UInt64)getValueOfMinute();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSecond())
            {
                ret[pMasqueradingVector[7]]=(Json::UInt64)getValueOfSecond();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getT1())
            {
                ret[pMasqueradingVector[8]]=(Json::UInt64)getValueOfT1();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getT2())
            {
                ret[pMasqueradingVector[9]]=(Json::UInt64)getValueOfT2();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getIdCounter())
    {
        ret["id_counter"]=(Json::UInt64)getValueOfIdCounter();
    }
    else
    {
        ret["id_counter"]=Json::Value();
    }
    if(getYear())
    {
        ret["year"]=(Json::UInt64)getValueOfYear();
    }
    else
    {
        ret["year"]=Json::Value();
    }
    if(getMonth())
    {
        ret["month"]=(Json::UInt64)getValueOfMonth();
    }
    else
    {
        ret["month"]=Json::Value();
    }
    if(getDay())
    {
        ret["day"]=(Json::UInt64)getValueOfDay();
    }
    else
    {
        ret["day"]=Json::Value();
    }
    if(getHour())
    {
        ret["hour"]=(Json::UInt64)getValueOfHour();
    }
    else
    {
        ret["hour"]=Json::Value();
    }
    if(getMinute())
    {
        ret["minute"]=(Json::UInt64)getValueOfMinute();
    }
    else
    {
        ret["minute"]=Json::Value();
    }
    if(getSecond())
    {
        ret["second"]=(Json::UInt64)getValueOfSecond();
    }
    else
    {
        ret["second"]=Json::Value();
    }
    if(getT1())
    {
        ret["T1"]=(Json::UInt64)getValueOfT1();
    }
    else
    {
        ret["T1"]=Json::Value();
    }
    if(getT2())
    {
        ret["T2"]=(Json::UInt64)getValueOfT2();
    }
    else
    {
        ret["T2"]=Json::Value();
    }
    return ret;
}

bool Indicator::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("id_counter"))
    {
        if(!validJsonOfField(1, "id_counter", pJson["id_counter"], err, true))
            return false;
    }
    if(pJson.isMember("year"))
    {
        if(!validJsonOfField(2, "year", pJson["year"], err, true))
            return false;
    }
    if(pJson.isMember("month"))
    {
        if(!validJsonOfField(3, "month", pJson["month"], err, true))
            return false;
    }
    if(pJson.isMember("day"))
    {
        if(!validJsonOfField(4, "day", pJson["day"], err, true))
            return false;
    }
    if(pJson.isMember("hour"))
    {
        if(!validJsonOfField(5, "hour", pJson["hour"], err, true))
            return false;
    }
    if(pJson.isMember("minute"))
    {
        if(!validJsonOfField(6, "minute", pJson["minute"], err, true))
            return false;
    }
    if(pJson.isMember("second"))
    {
        if(!validJsonOfField(7, "second", pJson["second"], err, true))
            return false;
    }
    if(pJson.isMember("T1"))
    {
        if(!validJsonOfField(8, "T1", pJson["T1"], err, true))
            return false;
    }
    if(pJson.isMember("T2"))
    {
        if(!validJsonOfField(9, "T2", pJson["T2"], err, true))
            return false;
    }
    return true;
}
bool Indicator::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Indicator::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("id_counter"))
    {
        if(!validJsonOfField(1, "id_counter", pJson["id_counter"], err, false))
            return false;
    }
    if(pJson.isMember("year"))
    {
        if(!validJsonOfField(2, "year", pJson["year"], err, false))
            return false;
    }
    if(pJson.isMember("month"))
    {
        if(!validJsonOfField(3, "month", pJson["month"], err, false))
            return false;
    }
    if(pJson.isMember("day"))
    {
        if(!validJsonOfField(4, "day", pJson["day"], err, false))
            return false;
    }
    if(pJson.isMember("hour"))
    {
        if(!validJsonOfField(5, "hour", pJson["hour"], err, false))
            return false;
    }
    if(pJson.isMember("minute"))
    {
        if(!validJsonOfField(6, "minute", pJson["minute"], err, false))
            return false;
    }
    if(pJson.isMember("second"))
    {
        if(!validJsonOfField(7, "second", pJson["second"], err, false))
            return false;
    }
    if(pJson.isMember("T1"))
    {
        if(!validJsonOfField(8, "T1", pJson["T1"], err, false))
            return false;
    }
    if(pJson.isMember("T2"))
    {
        if(!validJsonOfField(9, "T2", pJson["T2"], err, false))
            return false;
    }
    return true;
}
bool Indicator::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Indicator::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Counter Indicator::getCounter(const drogon::orm::DbClientPtr &clientPtr) const {
    std::shared_ptr<std::promise<Counter>> pro(new std::promise<Counter>);
    std::future<Counter> f = pro->get_future();
    getCounter(clientPtr, [&pro] (Counter result) {
        try {
            pro->set_value(result);
        }
        catch (...) {
            pro->set_exception(std::current_exception());
        }
    }, [&pro] (const DrogonDbException &err) {
        pro->set_exception(std::make_exception_ptr(err));
    });
    return f.get();
}
void Indicator::getCounter(const DbClientPtr &clientPtr,
                           const std::function<void(Counter)> &rcb,
                           const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from Counter where id = ?";
    *clientPtr << sql
               << *idCounter_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Counter(r[0]));
                    }
               }
               >> ecb;
}
